package com.kidsguard.app.quiz

import com.kidsguard.app.data.Difficulty
import com.kidsguard.app.data.SportTask
import kotlin.random.Random

/**
 * 运动打卡任务库。
 *
 * 运动模块不做纸笔题——「跳绳标准是多少」这种选择题学不到任何东西。
 * 这里改成真实动作任务，孩子照着做完后点「完成了」，家长端能看到记录。
 *
 * 48 种动作 × 3 个难度档 × 3 个年级 = 432 种参数组合，铺满 600 个任务位（循环取用）。
 * 目标数量随年级和难度递增，动作要领写在 tip 里。
 */
object SportTaskBank {

    fun taskFor(grade: Int, index: Int): SportTask {
        val def = ACTIONS[index % ACTIONS.size]
        val d = Difficulty.of(index)
        val target = def.targets[grade.coerceIn(1, 3) - 1][d.idx]
        return SportTask(
            id = "sport_${grade}_$index",
            name = def.name,
            desc = def.desc(target),
            target = target,
            unit = def.unit,
            tip = def.tip
        )
    }

    /** 随机取一个任务，用于弹窗时派发（避免每次都是同一项） */
    fun randomTask(grade: Int, seed: Int): SportTask {
        val index = Random(seed).nextInt(600)
        return taskFor(grade, index)
    }

    private class Action(
        val name: String,
        val unit: String,
        /** [年级][难度档] → 目标数量 */
        val targets: List<List<Int>>,
        val desc: (Int) -> String,
        val tip: String
    )

    private val ACTIONS = listOf(
        Action("跳绳", "个",
            listOf(listOf(30, 60, 100), listOf(50, 90, 140), listOf(70, 120, 180)),
            { "连续跳绳 $it 个" },
            "手腕摇绳，脚尖轻点地，膝盖微屈缓冲"),
        Action("拍球", "下",
            listOf(listOf(20, 40, 60), listOf(30, 50, 80), listOf(40, 70, 100)),
            { "原地拍球 $it 下" },
            "手指张开控球，肘部带动手腕，眼睛看前方不看球"),
        Action("深蹲", "个",
            listOf(listOf(10, 15, 20), listOf(12, 18, 25), listOf(15, 22, 30)),
            { "标准深蹲 $it 个" },
            "双脚与肩同宽，腰背挺直，蹲到大腿与地面平行"),
        Action("开合跳", "个",
            listOf(listOf(15, 25, 40), listOf(20, 35, 50), listOf(25, 45, 65)),
            { "开合跳 $it 个" },
            "跳起时双脚分开、双手举过头顶，落地时并拢"),
        Action("高抬腿", "个",
            listOf(listOf(20, 30, 50), listOf(25, 40, 60), listOf(30, 50, 80)),
            { "原地高抬腿 $it 个" },
            "大腿抬到与地面平行，前脚掌着地，节奏均匀"),
        Action("平板支撑", "秒",
            listOf(listOf(15, 25, 40), listOf(20, 35, 50), listOf(30, 45, 70)),
            { "平板支撑 $it 秒" },
            "身体成一条直线，收紧腹部，不要塌腰或翘臀"),
        Action("单脚站立", "秒",
            listOf(listOf(10, 20, 30), listOf(15, 25, 40), listOf(20, 35, 50)),
            { "单脚站立 $it 秒（左右脚各一次）" },
            "脚踩实地面，膝盖微屈，双手可侧平举保持平衡"),
        Action("蛙跳", "个",
            listOf(listOf(8, 12, 18), listOf(10, 15, 22), listOf(12, 18, 26)),
            { "蛙跳 $it 个" },
            "半蹲起跳，落地时前脚掌先着地并缓冲"),
        Action("拉伸放松", "秒",
            listOf(listOf(20, 30, 45), listOf(25, 35, 50), listOf(30, 45, 60)),
            { "拉伸放松 $it 秒" },
            "重点拉伸大腿后侧和小腿，动作缓慢不弹动"),
        Action("原地小跑", "秒",
            listOf(listOf(30, 60, 90), listOf(40, 70, 110), listOf(50, 90, 130)),
            { "原地小跑 $it 秒" },
            "前脚掌着地，手臂自然摆动，呼吸保持均匀"),

        Action("仰卧起坐", "个",
            listOf(listOf(8, 12, 18), listOf(12, 18, 25), listOf(15, 22, 30)),
            { "仰卧起坐 $it 个" },
            "屈膝平躺，双手抱头，用腹部力量起身，下巴别碰胸口"),
        Action("俯卧撑", "个",
            listOf(listOf(5, 8, 12), listOf(8, 12, 16), listOf(10, 15, 20)),
            { "俯卧撑 $it 个（可屈膝撑）" },
            "双手与肩同宽，身体一条直线，肘部向身体收"),
        Action("波比跳", "个",
            listOf(listOf(5, 8, 12), listOf(8, 12, 16), listOf(10, 15, 20)),
            { "波比跳 $it 个" },
            "下蹲 → 撑地 → 跳伸 → 收回 → 向上跳，动作连贯"),
        Action("弓步蹲", "个",
            listOf(listOf(8, 12, 16), listOf(10, 15, 20), listOf(12, 18, 24)),
            { "左右弓步蹲各 $it 个" },
            "前腿屈膝 90°，后腿膝盖下压，上身挺直"),
        Action("提踵", "个",
            listOf(listOf(15, 25, 40), listOf(20, 30, 50), listOf(25, 40, 60)),
            { "踮脚提踵 $it 个" },
            "脚跟尽量抬高，顶端停一秒再缓慢落下"),
        Action("靠墙静蹲", "秒",
            listOf(listOf(15, 25, 40), listOf(20, 35, 50), listOf(30, 45, 70)),
            { "靠墙静蹲 $it 秒" },
            "背贴墙，大腿与地面平行，膝盖不超脚尖"),
        Action("摸高跳", "个",
            listOf(listOf(8, 12, 18), listOf(10, 15, 22), listOf(12, 18, 26)),
            { "原地纵跳摸高 $it 个" },
            "屈膝摆臂全力起跳，单手上伸摸最高点"),
        Action("立定跳远", "次",
            listOf(listOf(6, 8, 10), listOf(8, 10, 12), listOf(10, 12, 15)),
            { "立定跳远 $it 次" },
            "预摆后双脚同时起跳，落地屈膝缓冲"),
        Action("登山跑", "个",
            listOf(listOf(15, 25, 40), listOf(20, 30, 45), listOf(25, 40, 55)),
            { "登山跑 $it 个（左右各算一次）" },
            "俯撑姿势，双腿交替向胸口收，核心收紧"),
        Action("侧弓步", "个",
            listOf(listOf(8, 12, 16), listOf(10, 15, 20), listOf(12, 18, 24)),
            { "左右侧弓步各 $it 个" },
            "向侧跨步下蹲，重心放支撑腿，上身保持正直"),
        Action("熊爬", "米",
            listOf(listOf(5, 8, 12), listOf(8, 12, 16), listOf(10, 15, 20)),
            { "熊爬 $it 米" },
            "手脚撑地、膝盖离地，对侧手脚同时前进"),
        Action("螃蟹走", "米",
            listOf(listOf(5, 8, 12), listOf(8, 12, 16), listOf(10, 15, 20)),
            { "螃蟹走 $it 米" },
            "仰撑或侧蹲姿势横向移动，臀部离地、手撑稳"),
        Action("鸭子步", "米",
            listOf(listOf(5, 8, 12), listOf(8, 12, 16), listOf(10, 15, 20)),
            { "鸭子步 $it 米" },
            "全蹲保持，双手背后或摆动，小步向前挪"),
        Action("折返跑", "次",
            listOf(listOf(6, 8, 10), listOf(8, 10, 12), listOf(10, 12, 15)),
            { "10 米折返跑 $it 次" },
            "全力冲出去，触线后急停转身，注意脚下别滑"),
        Action("后踢腿跑", "个",
            listOf(listOf(15, 25, 40), listOf(20, 30, 45), listOf(25, 40, 55)),
            { "后踢腿跑 $it 个" },
            "脚跟向后踢向臀部，前脚掌着地，快速交替"),
        Action("侧向滑步", "米",
            listOf(listOf(6, 10, 15), listOf(10, 15, 20), listOf(12, 18, 25)),
            { "侧向滑步 $it 米" },
            "两脚不交叉，横向快速移动，重心压低"),

        Action("转呼啦圈", "秒",
            listOf(listOf(10, 20, 30), listOf(15, 25, 40), listOf(20, 35, 50)),
            { "转呼啦圈 $it 秒" },
            "腰腹带动呼啦圈，保持匀速别用蛮力"),
        Action("踢毽子", "个",
            listOf(listOf(5, 10, 15), listOf(8, 12, 20), listOf(10, 15, 25)),
            { "踢毽子 $it 个" },
            "用脚内侧踢，眼睛盯住毽子，控制力度"),
        Action("颠乒乓球", "个",
            listOf(listOf(10, 15, 25), listOf(15, 25, 40), listOf(20, 30, 50)),
            { "颠乒乓球 $it 个" },
            "球拍放平，手腕小幅发力，让球垂直弹起"),
        Action("抛接球", "个",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "自抛自接球 $it 个" },
            "抛过头顶再双手接住，眼睛始终跟随球"),
        Action("原地投篮", "个",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "原地投篮 $it 个" },
            "屈膝蹬地、伸臂压腕，手指拨球出手"),
        Action("足球颠球", "个",
            listOf(listOf(3, 6, 10), listOf(5, 8, 12), listOf(8, 12, 18)),
            { "脚背颠球 $it 个" },
            "用脚背正面颠球，脚尖微翘，力度均匀"),

        Action("前滚翻", "个",
            listOf(listOf(3, 5, 8), listOf(5, 8, 12), listOf(6, 10, 15)),
            { "前滚翻 $it 个" },
            "低头团身，后脑着垫，抱膝滚动（注意软垫）"),
        Action("燕式平衡", "秒",
            listOf(listOf(5, 8, 12), listOf(8, 12, 18), listOf(10, 15, 22)),
            { "燕式平衡 $it 秒" },
            "单脚站立，上身前倾，后腿抬起与地面平行"),
        Action("闭眼单脚站", "秒",
            listOf(listOf(5, 8, 12), listOf(8, 12, 18), listOf(10, 15, 22)),
            { "闭眼单脚站立 $it 秒" },
            "闭上双眼保持平衡，可让家长在旁保护"),
        Action("靠墙倒立", "秒",
            listOf(listOf(5, 10, 15), listOf(8, 12, 20), listOf(10, 15, 25)),
            { "靠墙倒立 $it 秒" },
            "面墙双手撑地，腿依次上摆贴墙，家长须在旁保护"),

        Action("臀桥", "个",
            listOf(listOf(8, 12, 18), listOf(10, 15, 22), listOf(12, 18, 26)),
            { "臀桥 $it 个" },
            "仰卧屈膝，臀部发力向上顶，肩背贴地"),
        Action("仰卧举腿", "个",
            listOf(listOf(8, 12, 18), listOf(10, 15, 22), listOf(12, 18, 26)),
            { "仰卧举腿 $it 个" },
            "平躺双腿并拢抬起再放下，下腹发力别甩腿"),
        Action("超人式", "秒",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "俯卧超人式 $it 秒" },
            "俯卧同时抬起双臂双腿，像超人飞行"),
        Action("死虫式", "个",
            listOf(listOf(8, 12, 16), listOf(10, 15, 20), listOf(12, 18, 24)),
            { "死虫式 $it 个（左右各算一次）" },
            "仰卧手脚朝天，对侧手脚缓慢下放再收回"),
        Action("猫式伸展", "个",
            listOf(listOf(8, 12, 16), listOf(10, 15, 20), listOf(12, 18, 24)),
            { "猫式伸展 $it 个" },
            "四足跪姿，拱背低头再塌腰抬头，缓慢交替"),

        Action("体前屈", "秒",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "站立体前屈 $it 秒" },
            "双腿伸直，慢慢弯腰够脚尖，不弹动"),
        Action("弓步压腿", "秒",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "弓步压腿 $it 秒（左右各半）" },
            "前腿弓后腿蹬直，重心下沉，感受大腿前侧拉伸"),
        Action("坐位体前屈", "秒",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "坐位体前屈 $it 秒" },
            "坐地双腿伸直，缓慢前伸够脚尖，膝盖别弯"),
        Action("肩部绕环", "个",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "肩部绕环 $it 个（前后各半）" },
            "双臂伸直大幅画圈，先向前再向后"),
        Action("扩胸运动", "个",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "扩胸运动 $it 个" },
            "双臂向后扩胸，肩胛骨向后夹紧"),
        Action("体侧拉伸", "秒",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "体侧拉伸 $it 秒（左右各半）" },
            "单手叉腰、另一手上举向侧弯，感受腰部拉伸"),
        Action("转体扭腰", "个",
            listOf(listOf(10, 15, 20), listOf(15, 20, 30), listOf(20, 30, 40)),
            { "转体扭腰 $it 个（左右各半）" },
            "双脚开立，双手抱头左右转体，幅度逐渐加大")
    )
}
